version: "3.9"
services:
  proxy:
    image: nginx:1.23.3
    ports:
      - "0.0.0.0:8080:80"
    volumes:
      - ./proxy/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./proxy/static:/usr/share/nginx/static:ro
  web:
    build:
      context: ./web
      dockerfile: .devcontainer/Dockerfile
      args:
        - image_tag=3.2.0-bullseye
        - uid=1000
        - gid=1000
        - app_root=/workspaces/x-accel-redirect/web
    environment:
      - RAILS_HOSTS=web
    volumes:
      - ./web:/workspaces/x-accel-redirect/web
    expose:
      - 3000
    ports:
      - "0.0.0.0:8081:3000" # DEBUG
    command: /usr/bin/env bash -c 'bundle && rails s -b 0.0.0.0 -p 3000'
networks:
  default:
    name: x-accel-redirect_default
    external: true
