version: "3.9"
services:
  proxy:
    image: nginx:1.23.3
    ports:
      - "0.0.0.0:8080:80"
    volumes:
      - ./proxy/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./proxy/static:/usr/share/nginx/static:ro
networks:
  default:
    name: x-accel-redirect_default
    external: true
