upstream rate-limit-proxy {
    server proxy:81;
}

upstream rate-limit-web {
    server proxy:82;
}

server {
    listen       80;
    server_name  localhost;

    proxy_connect_timeout 1s;
    proxy_send_timeout 3s;
    proxy_read_timeout 3s;

    # ================================ #
    #        Nginx Static Files        #
    # ================================ #

    location /proxy/static {
        alias /usr/share/nginx/static;
    }

    # ================================ #
    #            Rails Data            #
    # ================================ #

    location = /web/download {
        proxy_pass http://rate-limit-web/public/download/;
    }

    location = /internal/download {
        internal;
        proxy_pass http://rate-limit-web/storage/download/;
    }

    # ================================ #
    #              Errors              #
    # ================================ #

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}
